### ISSUE TITLE
Document release processes for Operator

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/operator#1031]
Document what the release process looks like:

- the release manager role
- how version numbers are used and their meaning
- the release frequency 
- the steps to perform a major and a minor release

Include the links to existing / new documents in the issue.

**Comment by solacelost** [comment]
I would appreciate it if the release steps included upgrading the helm chart to prepare for the release as well, or if the helm chart were moved to another repository and/or versioned more carefully. At the moment, PRs like [this one](https://github.com/tektoncd/operator/pull/1019) come in after a [tag](https://github.com/tektoncd/operator/blob/v0.61.0/chart/Chart.yaml). Since I can't find a documented public location that the chart is published to, pulling the chart from [main](https://github.com/tektoncd/operator/blob/main/chart/Chart.yaml) and forcing the downloaded ref to main and setting the image tags may result in unexpected changes to resources other than the deployments.

I see that the chart currently is versioned to match the appVersion, but I don't have any reason to expect that this (recent) change will continue.

The chart would be fine to continue to co-locate with the operator, as long as the version bump to the chart on main following tag and image publish is well-understood and versioned charts are published to an official source.

Thanks! :)

**Comment by afrittoli** [comment]
Example from pipeline: https://github.com/tektoncd/pipeline/blob/main/releases.md

**Comment by afrittoli** [comment]
https://github.com/tektoncd/operator/pull/1104

This does not include yet what @solacelost requested, I'd let the operator maintainers work on that part 🙏

**Comment by afrittoli** [comment]
@vdemeester @solacelost Would you mind opening a separate issue for helm part, since this issue is part of a project that is now closed?
