### ISSUE TITLE
Operator Update Resets Pipeline as Code Config Map

### ISSUE THREAD

**Issue by David-N-Perkins** [tektoncd/operator#1373]
# Expected Behavior
When a patch update is pushed, any existing values in the `pipeline-as-code` config map should not change.

# Actual Behavior
When the Red Hat OpenShift Pipelines operator updated to `1.9.1` & `1.9.2`, the existing `pipeline-as-code` config map was changed to the default values. Specifically, `secret-github-app-token-scoped` was changed back to `true`. 

# Steps to Reproduce the Problem
1. Install Red Hat OpenShift Pipelines operator `1.9.1`
2. Change some of the `pipeline-as-code` config map entries
3. Upgrade Red Hat OpenShift Pipelines operator to `1.9.2`

# Additional Info

OpenShift version:  4.11.0-0.okd-2022-11-05-030711
Kubernetes version:  v1.24.0-2566+5157800f2a3bc3-dirty

Red Hat OpenShift Pipelines 1.9.2, which includes:
Tekton Pipelines: v0.41.1
Tekton Triggers: v0.22.1
Pipelines as Code: 0.15.5
Tekton Chains (tech-preview): v0.13.1
Tekton Hub (tech-preview): v1.11.3

**Comment by savitaashture** [comment]
When Pipelines as Code installed through Operator then configuration for PAC has to be changed via TektonConfig CR https://github.com/tektoncd/operator/blob/main/pkg/apis/operator/v1alpha1/tektonconfig_types.go#L100 

Otherwise what happens is in the next upgrade the `pipeline-as-code` config map  values changed to default values

**Comment by David-N-Perkins** [comment]
Thanks for the information. I found the TektonConfig and updated the configuration there.
