### ISSUE TITLE
Support seamless upgrade with Operator

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/operator#294]
### Feature request

Operator should allow seamless upgrade similar to other project like `Pipeline` and `Triggers`

Currently the upgrade steps are
1. Install old version of Operator
2. Install `Config` CR
3. Install new version of Operator

**Comment by houshengbo** [comment]
The new version of the operator should recognize the existing CRs automatically and reconcile.
I do not think there should be any need to touch on the existing CRs during the upgrade.

**Comment by nikhil-thomas** [comment]
@savitaashture @vdemeester is this issue still valid. 🧑‍💻 As TektonInstallerSet ensusers seamless upgrade of all resources except CRDs by doing "replace"(delete- create) instead of in-place upgrade.

What we can add is an upgrade test in our e2e tests (or release tests) where the operator tries to ugrade from n-1 release version.

**Comment by vdemeester** [comment]
Agreed, aside from a e2e tests, this is probably close-able
