### ISSUE TITLE
CR status is always true while reconciling for changes

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#346]
When a user make changes in the CR for eg. `TektonConfig`, it takes a bit of time to reach desired state,
during this time the status of CR is always true which is kind of misleading.
Although if it fails while reconciling it will set the status of CR as false and show the error.

There should be indication when the resource is reconciling and not in desired state.
But also this shouldn't keep changing the status on each reconcile.

Currently, when the CR status becomes true, it will change only if there is some error. 

We need more checks in the reconcilation. 
for example:
When reconciling for `TektonPipelines`, currently we apply the manifest everytime
But we can have a check 
```
if (status of deployment != true) {
  set status to reconciling or pending 
  and then do the changes to bring the resource to desired state
}
```

**Comment by sm43** [comment]
@nikhil-thomas @pradeepitm12 @vdemeester any thoughts?

**Comment by nikhil-thomas** [comment]
This a part of our reconciler(s) which can be enhanced with better checks are early returns instead of executing the full reconcile steps in every reconcile trigger.

We need to rethink "stages/checkpoints" in our reconcile logic. This might also need modfications to the status design too.

What I suggest is to create a design doc on this and we can colaborate/reason out an improved reconcile flow.

**Comment by nikhil-thomas** [comment]
@sm43 does the recent refactoring of the reconcilers address this.
if yes, let us close this. 🧑‍💻
