### ISSUE TITLE
Configurable resource limits/requests for CPU and memory

### ISSUE THREAD

**Issue by jb-2020** [tektoncd/operator#589]
### Feature request

Currently, the deployments for the operator and the corresponding Tekton components (e.g. `tekton-dashboard`) do not have resource requests.  Please provide a method of configuration or sane defaults for memory and CPU limits and requests. 

### Use case

Rightsizing our Tekton resources.

**Comment by nikhil-thomas** [comment]
> sane defaults for memory and CPU limits and requests.

could be addressed immediately 🧑‍💻 👍 

> a method of configuration 

there are 2 ways to approach this: 

1. provide a way to customize this throught TektonConfig CRD or through some other customization mechanism (eg: a ConfigMap)
2. leave thsese fields in a deployment spec (limits and request) unmanaged, like we do with deployment `replicas` so that an end user can set it independently without being reset by operator.

**Comment by nikhil-thomas** [comment]
related to https://github.com/tektoncd/operator/issues/580
