### ISSUE TITLE
Customize namespaces of Webhooks

### ISSUE THREAD

**Issue by jacksgt** [tektoncd/operator#624]
Hello,

is it possible to change the location where the Webhooks are supposed to be deployed?

When installing the operator with the release YAML, I can change the location where the Webhook deployment and service are deployed.
However, the *expected* location (as indicated in the `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration`) is still hard-coded to `tekton-operator` / `openshift-operators`:

https://github.com/tektoncd/operator/blob/e4ca6e1505d047e97122e122073c3fbc620b0f16/cmd/openshift/webhook/kodata/validating-defaulting-webhook/500_webhooks.yaml#L29

https://github.com/tektoncd/operator/blob/e4ca6e1505d047e97122e122073c3fbc620b0f16/cmd/kubernetes/webhook/kodata/validating-defaulting-webhook/500-webhooks.yaml#L28

**Comment by vdemeester** [comment]
@jacksgt this is only for the operator webhooks themselves right ?

**Comment by jacksgt** [comment]
Yes, here I'm only referring to the Webhooks deployed directly by the operator.

**Comment by jacksgt** [comment]
In principal this should not be difficult to adjust, because the operator already has the `SYSTEM_NAMESPACE` environment variable.
I'm just not familiar with the codebase and don't know where the correct place to inject this modification is, otherwise I'm happy to contribute a PR :-)

**Comment by Miles-Garnsey** [comment]
I am also having some problems with this. When I apply the manifests (e.g. [here](https://storage.googleapis.com/tekton-releases/operator/latest/release.yaml) and they are deployed in a custom namespace (e.g. `operators`) I see namespace-related webhook errors when I try to apply a `TektonConfig`:

```
for: "STDIN": Internal error occurred: failed calling webhook "webhook.operator.tekton.dev": Post "https://tekton-operator-webhook.tekton-operator.svc:443/defaulting?timeout=10s": service "tekton-operator-webhook" not found
```

This should not be happening, because the manifests (which I linked above) actually do set `SYSTEM_NAMESPACE` for all deployments, and (because it has `valueFrom` metadata.namespace) this should be set to `operators`. 

So the fact that the webhook service is expected to be at `tekton-operator-webhook.tekton-operator.svc` (from the error message) indicates that the `SYSTEM_NAMESPACE` is not being picked up correctly somewhere within the operator itself.

**Comment by vdemeester** [comment]
/cc @sm43 @nikhil-thomas 
I think this is fixed by https://github.com/tektoncd/operator/pull/637 ?

**Comment by nikhil-thomas** [comment]
yes, https://github.com/tektoncd/operator/pull/637 shoud fix this

**Comment by vdemeester** [comment]
Let's close it then 👼🏼 
/close
