### ISSUE TITLE
How do you set the versions for the components you want the operator to install?

### ISSUE THREAD

**Issue by spstarr** [tektoncd/operator#887]
It's not clear to me how to tell the Tekton Operator what versions of `pipelines` `dashboard` etc to install, the documentation mentions nothing about this.

So, how does a user want to update the version? Say from Tekton 0.37 -> 0.37.1?

I would have thought https://github.com/tektoncd/operator/blob/main/docs/TektonConfig.md explains this since you use a `TektonConfig` to manage components to install...

**Comment by vdemeester** [comment]
> It's not clear to me how to tell the Tekton Operator what versions of `pipelines` `dashboard` etc to install, the documentation mentions nothing about this.
> 
> So, how does a user want to update the version? Say from Tekton 0.37 -> 0.37.1?
> 
> I would have thought https://github.com/tektoncd/operator/blob/main/docs/TektonConfig.md explains this since you use a `TektonConfig` to manage components to install...

A release of the operator ships with a certain set of versions, and the user cannot change that (otherwise, the support would become crazy difficult to do). 

Ideally, when a bugfix is released, let's say `v0.37.1`, all the operator releases that contains this version (aka `v0.37.0`) should bump the version and have themselves a new bugfix release. This should also be true for all the components. We are not there yet in terms of automation and sticking to this, but this is what we aim for.

*We are also lacking a bit in terms of documentation*.

/kind documentation

**Comment by spstarr** [comment]
Thanks, that clarifies, I was not expecting the Operator to be a fixed-component install, but that explains why it will reset components if overridden by newer versions.

**Comment by vdemeester** [comment]
fyi started to work a bit on that :
- https://github.com/tektoncd/operator/pull/897 as an immediate "let's bump to the latest pipeline release on the latest operator release"
- https://github.com/tektoncd/operator/pull/898 to have some tool to automate this
- next is more automation and a clearer documentation 👼🏼
